name: Build

on:
  push:
    branches:
      - "main"

  pull_request:
    branches:
      - "*"

# Cancel in progress runs for PRs but not main
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  LLVM_VER: 17
  PYTHON_VER: 3.11
  VCPKG_REGISTRY_VERSION: v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest-32x64
    container:
      image: ghcr.io/lifting-bits/cxx-common/vcpkg-builder-ubuntu-v2:22.04
      options: --user 1001

    permissions:
      contents: write
      packages: write

    steps:
      - name: Setup deploy keys
        run: |
          eval $(ssh-agent -s)
          ssh-add - <<< '${{ secrets.MX_REGISTRY_KEY }}'

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - run: git config --global --add safe.directory '*'

      - name: Install prereqs
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          curl -sSL https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -
          echo "deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-${LLVM_VER} main" | tee -a /etc/apt/sources.list > /dev/null
          echo "deb-src http://apt.llvm.org/jammy/ llvm-toolchain-jammy-${LLVM_VER} main" | tee -a /etc/apt/sources.list > /dev/null
          apt-get update; apt-get install gh clang-${LLVM_VER} lld-${LLVM_VER} python${PYTHON_VER} python${PYTHON_VER}-dev -y

      - name: Setup cmake
        uses: trail-of-forks/actions-setup-cmake@master
        with:
          cmake-version: '3.24.x'

      - name: Use cmake
        run: cmake --version

      - name: Set up variables
        run: |
          echo "RELEASE_DIR=${RUNNER_TEMP}/release" >> $GITHUB_ENV
          echo "VERSION=$(git rev-parse --short=7 HEAD)" >> $GITHUB_ENV
          echo "ARTIFACT_NAME=multiplier-$(git rev-parse --short=7 HEAD).tar.xz" >> $GITHUB_ENV
          echo "CC=$(which clang-$LLVM_VER)" >> $GITHUB_ENV
          echo "CXX=$(which clang++-$LLVM_VER)" >> $GITHUB_ENV
          echo "CFLAGS=-g0 --ld-path=$(which ld.lld-$LLVM_VER) -flto" >> $GITHUB_ENV
          echo "CXXFLAGS=-g0 --ld-path=$(which ld.lld-$LLVM_VER) -flto" >> $GITHUB_ENV
          echo "VCPKG_BINARY_SOURCES=clear;files,$GITHUB_WORKSPACE/vcpkg-binary-cache,readwrite" >> $GITHUB_ENV

      - name: Setup vcpkg
        run: |
          mkdir -p $GITHUB_WORKSPACE/vcpkg-binary-cache
          git clone https://github.com/microsoft/vcpkg $HOME/vcpkg
          $HOME/vcpkg/bootstrap-vcpkg.sh

      - name: Preseed vcpkg cache
        run: |
          gh release download $VCPKG_REGISTRY_VERSION vcpkg-binary-cache.tar.bz2 --repo trailofbits/multiplier-vcpkg-registry
          tar xjf vcpkg-binary-cache.tar.bz2
          rm vcpkg-binary-cache.tar.bz2
        env:
          GITHUB_TOKEN: ${{ secrets.MX_REGISTRY_RELEASES_TOKEN }}

      - name: Cache vcpkg binaries
        id: cache-vcpkg
        uses: actions/cache@v4
        with:
          path: $GITHUB_WORKSPACE/vcpkg-binary-cache
          key: ${{ runner.os }}-${{ hashFiles('vcpkg-registry/ports/**/*') }}
          restore-keys: |
            ${{ runner.os }}-${{ hashFiles('vcpkg-registry/ports/**/*') }}
            ${{ runner.os }}-

      - name: Build
        run: |
          cmake \
            -DVCPKG_TARGET_TRIPLET=x64-linux-rel \
            --toolchain "$HOME/vcpkg/scripts/buildsystems/vcpkg.cmake" \
            -DCMAKE_BUILD_TYPE=Release \
            -GNinja \
            -S . \
            -B build

          cmake --build build
          cmake --install build --prefix ${RELEASE_DIR}

      # Release on merge to main
      - name: Package Release
        if: github.ref == 'refs/heads/main'
        working-directory: ${{ env.RELEASE_DIR }}
        run: tar --use-compress-program pixz -cf "${ARTIFACT_NAME}" *

      - name: Create Release
        if: github.ref == 'refs/heads/main'
        run: gh release create ${VERSION} --generate-notes ${{ env.RELEASE_DIR }}/${{ env.ARTIFACT_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
